DFE-Digital/find-a-tuition-partner

README.md, UI/Pages/Shared/_Layout.cshtml, manifest.yml, vars-production.yml, vars-qa.yml, vars-research.yml, vars-staging.yml
We now have access to Google Analytics and have set up a property per environment with an associated data stream. We need to prove we can send metrics to GA.
Add Google Analytics global site tag that is enabled when the related environment variable is set.
GA measurement ids are not considered secrets as they are viewable in HTML source.
[NTP-255](https://dfedigital.atlassian.net/browse/NTP-255)
=> NTP-255: Add Google Analytics integration

DataImporter/Program.cs, FindATuitionPartner.sln, GiasPostcodeSearch/GiasPostcodeSearch.csproj, GiasPostcodeSearch/GiasPostcodeSearchService.cs, GiasPostcodeSearch/GiasSchoolDataProvider.cs, GiasPostcodeSearch/ISchoolDataProvider.cs, GiasPostcodeSearch/Program.cs, GiasPostcodeSearch/Properties/launchSettings.json, GiasPostcodeSearch/SchoolDatum.cs, GiasPostcodeSearch/appsettings.json, Infrastructure/DataEncryptionService.cs, Infrastructure/Infrastructure.csproj, docs/runbooks/performance-testing.md
Prior to going live, the team needs reassurance that the service will cope under reasonable launch day load. This load has been estimated as roughly the following:
Total eligible schools x five searches per school over an eight hour period:
(20188 x 5) / 8 / 60 = 210 searches per minute or around 3.5 per second
Realistically it is highly unlikely that all the schools will use the service on launch day however there is likely to be media interest in the service which could increase stats. A high end estimate of 10 searches per second will be used as a baseline.
The new `GiasPostcodeSearch` console app has been added to perform load testing. A custom app has been used because the eligible dataset is known and available from the GIAS service.
This is a utility console app which is why it is …
=> NTP-349/411: Performance testing using the GIAS dataset

Tests/TempData.cs, Tests/TuitionPartnerDetailsPage.cs, UI/Extensions/TempDataSerialisation.cs, UI/Pages/SearchResults.cshtml.cs, UI/Pages/TuitionPartner.cshtml, UI/Pages/TuitionPartner.cshtml.cs, UI/cypress/e2e/location-aware-results.feature, UI/cypress/e2e/results.js, UI/cypress/e2e/tuition-partner-details.js, UI/cypress/support/step_definitions/results-page.js, UI/cypress/support/utils.js
Tuition partners may provide different online and in-school services in different districts.  We want the Tuition partner details page to be aware of which district was searched for and only show the tuition type(s) relevant to that district.
As an example, Action Tutoring provides KS2 English tutors in-school and online to to S1 2PP, but only online to SK1 1EB.
When searching in the results page already reflects this
for S1 2PP:
for SK1 1EB:
The information page now also reflect this
for S1 2PP:
for SK1 1EB:
The end-to-end tests use live data to verify the tuition types are shown / not shown when appropriate.  This is the easiest way to write these tests as we currently have no way to manipulate the back-end data from cypress.
https://dfedigital.atlassian.net/browse/NTP-376
=> NTP-376: Make TP details page location aware

Application/Extensions/StringExtensions.cs, Domain/Search/TuitionPartnerSearchResult.cs, Tests/TuitionPartnerDetailsPage.cs, UI/Pages/SearchResults.cshtml, UI/Pages/TuitionPartner.cshtml, UI/Pages/TuitionPartner.cshtml.cs, UI/cypress/e2e/results.feature, UI/cypress/e2e/send-results.feature, UI/cypress/e2e/send-results.js, UI/cypress/support/step_definitions/results-page.js
Add a SEND row to the search results and tuition partner pages
https://dfedigital.atlassian.net/browse/NTP-285
=> NTP-285: Add SEND support to pages

UI/Pages/Shared/_Layout.cshtml, UI/cypress/e2e/phase-banner.feature, UI/cypress/e2e/phase-banner.js, UI/cypress/e2e/postcode.feature
The link used in the original PR was wrong.
[NTP-386](https://dfedigital.atlassian.net/browse/NTP-386)
=> NTP-386: Fix the feedback link and move e2e tests to own feature

UI/Pages/Shared/_Layout.cshtml, UI/package-lock.json, UI/webpack.config.js
Dependabot highlighted a potential vulnerability with an npm package. The govuk frontend team released a minor update which included a fix for JavaScript ES module imports.
There are no visual changes as a result of this update
[NTP-445](https://dfedigital.atlassian.net/browse/NTP-445)
[NTP-447](https://dfedigital.atlassian.net/browse/NTP-447)
=> NTP-445 and 447: npm update to resolve package vulnerability and upgrade to govuk frontend 4.2.0

Tests/SearchForSubjects.cs, UI/Pages/SearchModel.cs, UI/Pages/SearchResults.cshtml, UI/cypress/e2e/results.feature, UI/cypress/e2e/results.js, UI/cypress/e2e/subjects.js, UI/cypress/support/step_definitions/pages.js, UI/cypress/support/step_definitions/postcode.js, UI/cypress/support/step_definitions/subjects-page.js
* Add a back link to the search results page
* Move the "<n> results for <location>" to just above the results list
* Add "Sorted by A-Z"
Desktop view:
Tablet view:
Mobile view:
With postcode error:
https://dfedigital.atlassian.net/browse/NTP-314
=> NTP-314: Content update for search results page

Tests/TuitionPartnerDetailsPagePriceTable.cs, UI/Extensions/ToStringExtensions.cs, UI/Pages/TuitionPartner.cshtml, UI/Pages/_ViewImports.cshtml, UI/cypress/e2e/tuition-partner-details.feature, UI/cypress/e2e/tuition-partner-details.js
* Remove the entire column for a tuition type if it is not provided.
* Trim prices where they are whole pounds.
Before: 
After: 
https://dfedigital.atlassian.net/browse/NTP-378
=> NTP-378: Cost per subject content

Application/Handlers/SearchTuitionPartnerHandler.cs, Tests/SearchForResults.cs, Tests/Utilities/SliceFixture.cs, UI/Pages/Cookies.cshtml.cs, UI/Pages/SearchResults.cshtml.cs, UI/cypress/e2e/results.feature
While we use Local Authority Districts to define the tuition partner coverage, we want to display the more familiar Local Education Authority name to the users.
Previously a search for a postcode in the Dacorum LAD would display Dacorum:
It should have displayed the Hertfordshire LEA Dacorum is part of:
[NTP-460](https://dfedigital.atlassian.net/browse/NTP-460)
=> NTP-460: display LEA name rather than LAD name on results page

UI/Pages/Shared/_Layout.cshtml, UI/cypress/e2e/footer-support-link.feature, UI/cypress/e2e/footer-support-link.js
* Add a link to the support email address in the footer
https://dfedigital.atlassian.net/browse/NTP-385
=> NTP-385: Add support link to footer

Tests/OptionsSelectModelTests.cs, Tests/SearchForResults.cs, UI/Pages/SearchResults.cshtml, UI/Pages/SearchResults.cshtml.cs, UI/Pages/Shared/_OptionsSelect.cshtml.cs, UI/cypress/e2e/results.feature, UI/cypress/e2e/results.js, UI/cypress/support/step_definitions/errors.js, UI/cypress/support/step_definitions/results-page.js
Show all the tuition partners when there is no postcode entered and/or no subjects selected
https://dfedigital.atlassian.net/browse/NTP-375
=> NTP-375: Search results page with no search criteria

Infrastructure/Extensions/HostBuilderExtensions.cs, UI/Pages/TuitionPartner.cshtml
Removed tuition partner group info from tuition partner details page has this already shown in price info
Before:
After:
Tuition partner info should match the above screen shot
https://dfedigital.atlassian.net/browse/NTP-470
=> NTP-470:Removed tuition group size in tp information page

Application/Handlers/SearchTuitionPartnerHandler.cs, Application/Repositories/ITuitionPartnerRepository.cs, Domain/Search/TuitionPartnerOrdering.cs, Infrastructure/Repositories/TuitionPartnerRepository.cs, Tests/RandomiseSearchResults.cs, Tests/TuitionPartnerDetailsPagePriceTable.cs, UI/Pages/SearchResults.cshtml, UI/Pages/SearchResults.cshtml.cs, UI/cypress/e2e/results.js
Randomisation of search results list will avoid the appearance of preferential treatment towards those providers who would constantly appear at the top.  However, we would like to present the results in a consistent order for any given set of search criteria.  This would allow the search to be re-run later, or results URL to be shared with colleagues, and the same set of results in the same order will be seen.  
Search results for one set of search criteria will always return in the same order.  Change the criteria slightly and the order will be different.
Check that the results are always the same when searching for 
* [SK11EB KS1 Engligh](https://localhost:7036/search-results?Postcode=SK1%201EB&Subjects=KeyStage1-English&KeyStages=KeyStage1)
* [SK11EB KS1 English and …
=> NTP-462: Randomise search results

UI/Pages/AcademicMentors.cshtml, UI/Pages/Cookies.cshtml, UI/Pages/SearchResults.cshtml, UI/cypress/e2e/results.js
These are a couple of content fixes that came out of the team review last week
* [NTP-462](https://dfedigital.atlassian.net/browse/NTP-462) "Your search results are in a random order" should be below the result count
* [NTP-388](https://dfedigital.atlassian.net/browse/NTP-388) Heading size and typo on the Cookies page
* [NTP-379](https://dfedigital.atlassian.net/browse/NTP-379) Capitalise list items on Academic Mentors page
* [NTP-314](https://dfedigital.atlassian.net/browse/NTP-314) Search page title, and result count is 24px
=> NTP-462: Content fixes

.github/workflows/continuous-deployment-to-qa.yml, .github/workflows/deploy-to-gpaas.yml, .github/workflows/end-to-end-testing.yml, UI/Pages/Index.cshtml, UI/package-lock.json, UI/package.json, docs/decisions/0001-use-gpaas-hosting-environment.md, docs/runbooks/manual-environment-setup.md, docs/runbooks/manual-environment-teardown.md, docs/runbooks/performance-testing.md, manifest.yml, terraform/paas/sandbox.env.tfvars, terraform/paas/variables.tf, vars-production.yml, vars-staging.yml
GDS have agreed to find-tuition-partner.service.gov.uk as the service domain. We want to rename the GPaaS components from national-tuition to find-a-tuition-partner in preparation for this.
- Create find-a-tuition-partner-<ENVIRONMENT> application and find-a-tuition-partner-<ENVIRONMENT>-postgres-db backing database service GPaaS components
- Remove all national-tutoring-<ENVIRONMENT> GPaaS components
- Remove basic http authentication 
(NTP-472)[https://dfedigital.atlassian.net/browse/NTP-472]
=> NTP-472: Move GPaaS components over to find-a-tuition-partner

Tests/TuitionPartnerDetailsPage.cs, UI/Pages/TuitionPartner.cshtml.cs, UI/cypress/e2e/location-aware-results.feature, UI/cypress/e2e/tuition-partner-details.feature, UI/cypress/support/step_definitions/results-page.js
Before: A search for [KS1 English in SK11EB with any tuition](https://localhost:7036/search-results?Data.Subjects=KeyStage2-English&Data.TuitionType=Any&Data.Postcode=SK1+1EB) shows
After:
https://dfedigital.atlassian.net/browse/NTP-451
=> NTP-451: Only show prices for the searched tuition type

Tests/TuitionPartnerDetailsPage.cs, UI/Pages/TuitionPartner.cshtml, UI/Pages/TuitionPartner.cshtml.cs, UI/cypress/e2e/tuition-partner-details.feature, UI/cypress/e2e/tuition-partner-details.js
When prices do not vary, the text says "all subjects are the same price"
When prices do vary, the text says "some prices are different depending on key stage or subject."
https://dfedigital.atlassian.net/browse/NTP-453
=> NTP-452: Highlight when cost information differs by subject

UI/Pages/Cookies.cshtml.cs, UI/Pages/Shared/_Layout.cshtml
Services similar to ours have reported that the rates for opting into Google Analytics cookies are low at around 25%. This makes extrapolating usage of the service potentially inaccurate.
GA has supported consent mode since 2020 allowing users to deny consent to the parts of GA that rely on cookies for session and advertising needs. This means it is possible for users to opt out of the _cookies_ used for full GA tracking but for us to still track basic usage of the side e.g. page titles, URLs, user agents etc.
We want to use consent mode during public beta to discover if these reduced metrics still provide the KPIs needed to evaluate the service. 
No user visible changes. The key code changes are:
- Post -> redirect -> get implemented on the cookies page. The current implementation …
=> NTP-516: Default all GA cookie related consent to denied

UI/Pages/Error.cshtml, UI/cypress/e2e/error-handling.js
Titles are needed for pages
Added html titles for error page and added end to end test check for title for 'page not found'. No end to end test for 'problem with service' as the error cannot be created at this point to test
No
https://dfedigital.atlassian.net/browse/NTP-513
=> NTP-513: Added html titles for error pages

UI/Pages/FundingAndReporting.cshtml
Header Class should be l rather than xl to be consists around the pages
Before:
After:
Header class should be L Not Xl
https://dfedigital.atlassian.net/browse/NTP-381
=> NTP-381:fixed the header class for funding and reporting page

UI/Pages/Index.cshtml, UI/Pages/Shared/_Layout.cshtml, UI/cypress/e2e/phase-banner.feature
We're scheduled to move into public beta on the 17th of August along with soft launching the service.
* Re-enable indexing of the production start page
* Change the phase banner to beta
(NTP-527)[https://dfedigital.atlassian.net/browse/NTP-527]
=> NTP-527: Move into public beta

UI/Pages/FundingAndReporting.cshtml, UI/Pages/Privacy.cshtml, UI/cypress/e2e/privacy.js
Change in main header for privacy page and content change in funding page
Before:
After:
Content should match as per comments made in the userstory
https://dfedigital.atlassian.net/browse/NTP-381
https://dfedigital.atlassian.net/browse/NTP-389
=> NTP-389:Content change for privacy,funding page

UI/Pages/SearchResults.cshtml, UI/src/sass/results-filter.scss
The gap between the postcode input box and search button on the search results screen was too narrow. Additionally the mobile view of this inline input element did not expand the input box appropriately.
Before (desktop):
Before (tablet and below):
After (desktop)
After (tablet and below):
This is a foundational ticket for the search results mobile view.
(NTP-459)[https://dfedigital.atlassian.net/browse/NTP-459]
=> NTP-459: Set correct left margin for search results postcode button

UI/Pages/Privacy.cshtml
added the correct header class
Before:
After:
Header class should be l
https://dfedigital.atlassian.net/browse/NTP-389
=> NTP-389:Header Class change from xl to l

Application/Handlers/SearchTuitionPartnerHandler.cs, GiasPostcodeSearch/GiasPostcodeSearchService.cs, Infrastructure/Extensions/ServiceCollectionDecorationExtensions.cs, Infrastructure/Extensions/ServiceCollectionExtensions.cs, Infrastructure/Extensions/ServiceCollectionLoggingExtensions.cs, Infrastructure/LoggingLocationFilterService.cs, Infrastructure/MetricLogging/LoggingLocationFilterService.cs, Infrastructure/MetricLogging/SearchTuitionPartnerHandlerLoggingBehaviour.cs, Tests/Utilities/SliceFixture.cs, UI/Filters/ExceptionLoggingMiddleware.cs, UI/Program.cs
Log key events that will be used to generate metrics.
We now log the postcode lookup, the search results and any uncaught exceptions.
Below is an example log when we process the search results ([view in Logit.io](https://kibana.logit.io/s/5a330412-9270-4c5b-ba07-0035bf55fe95/app/discover#/doc/8ac115c0-aac1-11e8-88ea-0383c11b333a/logstash-2022.08.12?id=ALbtk4IBuoNUndCWtFzS)).  Notice that we attach the search request to the log context so that the log line with the results also includes what was searched for.
```json
{
"_source": {
"message": "Found 41 results in 409ms",
"tuitionPartners": [
"Tuition Partner 1",
"Tuition Partner 2",
"Tuition Partner 3\t",
"Tuition Partner 4\t",
],
"@version": "1",
"environmentName": "Development",
"@timestamp": "2022-08-12T21:20:05.124Z",
"sourceContext": …
```
=> Ntp 425 log key events

UI/Pages/Shared/_Layout.cshtml
Changed the text of privacy link in the footer to privacy
Before:
After:
Name of the link is changed to Privacy
https://dfedigital.atlassian.net/browse/NTP-389
=> NTP-389: footer privacy link text change

UI/Pages/FundingAndReporting.cshtml
Fix the maths in the funding details example.
https://dfedigital.atlassian.net/browse/NTP-381?focusedCommentId=47595
=> NTP-381: Funding details content correction

UI/Pages/Cookies.cshtml, UI/Program.cs, UI/cypress/e2e/security-headers.feature, UI/cypress/e2e/security-headers.js
Security risks have been highlighted by the absence of security headers in the Assessment.
Adding following security headers:
X-Frame-Options
Content-Security-Policy
X-XSS-Protection
X-Content-Type-Options
https://dfedigital.atlassian.net/browse/NTP-528
=> NTP-528: resolve missing http security headers

.gitignore, UI/Pages/TriggerError.cshtml, UI/Pages/TriggerError.cshtml.cs
http://localhost:7036/trigger-exception will throw and log exception and show the error page.
https://dfedigital.atlassian.net/browse/NTP-450
=> NTP-450: A page that intentionally throws an exception and shows the error page

UI/Pages/Cookies.cshtml, UI/Pages/Cookies.cshtml.cs, UI/Pages/FundingAndReporting.cshtml, UI/Pages/FundingAndReporting.cshtml.cs, UI/Pages/Shared/_CookiesOptionBanner.cshtml, UI/Pages/Shared/_Layout.cshtml, UI/Program.cs, UI/cypress/e2e/cookies.feature, UI/cypress/e2e/cookies.js
[OWASP Zed Attack Proxy](https://www.zaproxy.org/) tool has detected a potential vulnerability on the cookies page due to its use of query string parameters this pr should fix the issue 
After:
when you run the following url https://localhost:7036/ locally with this branch in zap it should not throw the security vulnerability issues
https://dfedigital.atlassian.net/browse/NTP-534
=> NTP-534: fixed the bug related to Security vulnerability on cookies page

UI/Pages/SearchResults.cshtml, UI/Pages/TuitionPartner.cshtml, UI/cypress/e2e/mobile.feature, UI/cypress/e2e/mobile.js, UI/src/index.scss, UI/src/sass/mobile-views.scss
When viewing the application via a phone subjects need to be listed with bullet pointed
Pages SearchResults and TuitionPartner have the subject list bullet pointed when viewing application via phone
**In desk top view**
**In Mobile view**
Use tool on browser to emulate viewing via mobile views. 
https://dfedigital.atlassian.net/browse/NTP-532
=> NTP-532: mobile views bullet points

Domain/Search/TuitionPartnerOrdering.cs, Domain/Search/TuitionPartnerSearchRequest.cs, Tests/RandomiseSearchResults.cs, UI/Pages/SearchResults.cshtml.cs
The current implementation of the search order randomiser uses only the LAD code as part of the random seed. This means that if two schools in the same LAD search with the same subject list, they will see the same ordering of TPs. This is considered a problem by the TPs.
Add the postcode as part of the random seed generator to make every postcode's results order differently
[NTP-465](https://dfedigital.atlassian.net/browse/NTP-465)
=> NTP-465: Use postcode for randomiser

Infrastructure/Repositories/TuitionPartnerRepository.cs, UI/Pages/SearchResults.cshtml, UI/Pages/TuitionPartner.cshtml, UI/cypress/e2e/results.feature, UI/cypress/e2e/results.js, UI/cypress/e2e/tuition-partner-details.feature, UI/cypress/support/step_definitions/results-page.js
Tuition types are missing when searches without postcodes are made. 
Change database query to return tuition types and end to end tests
**Before changes**
**After Changes:**
https://dfedigital.atlassian.net/browse/NTP-567
=> NTP-567: Added fix for missing tuition types and end to end tests

UI/Pages/AcademicMentors.cshtml, UI/Pages/SchoolLedTutoring.cshtml, UI/cypress/e2e/academicmentors.js
The Tutor Training link has changed.
https://dfedigital.atlassian.net/browse/NTP-587
=> NTP-587: Update tutor training registration link

UI/Pages/Index.cshtml, UI/Pages/WhichKeyStages.cshtml, UI/cypress/e2e/subjects.js, UI/cypress/e2e/tuition-partner-user-journey.feature, UI/cypress/e2e/tuition-partner-user-journey.js, UI/cypress/support/step_definitions/pages.js, UI/cypress/support/step_definitions/subjects-page.js
Data selections are lost when navigating back along the application's journey
Go back and forth along the Find a Tutor journey and make sure selections are maintained and edits work. 
https://dfedigital.atlassian.net/browse/NTP-544
=> NTP-544: back from search results to key stage and continue clears subjects

Infrastructure/Repositories/TuitionPartnerRepository.cs, UI/Pages/SearchResults.cshtml, UI/Pages/TuitionPartner.cshtml, UI/cypress/e2e/results.feature, UI/cypress/e2e/results.js, UI/cypress/e2e/tuition-partner-details.feature, UI/cypress/support/step_definitions/results-page.js
Tuition types are missing when searches are made without postcodes
**Before:**
**After:**
Query has been changed so testing of searches should be done with and without postcodes. 
https://dfedigital.atlassian.net/browse/NTP-567
=> NTP-567: type of tuition is blank when no postcode is specified

UI/Pages/AcademicMentors.cshtml, UI/Pages/SchoolLedTutoring.cshtml, UI/cypress/e2e/academicmentors.js, UI/cypress/e2e/schoolledtutoring.feature, UI/cypress/e2e/schoolledtutoring.js
A link on the Academic Mentors page had been copied from the School Led Tuition page. The rest of the ticket had already been completed.
https://dfedigital.atlassian.net/browse/NTP-587
=> NTP-587: Correct a copy paste content error on the AM page

UI/Pages/Cookies.cshtml.cs, UI/Pages/Shared/_Layout.cshtml, UI/Pages/_ViewImports.cshtml, UI/Program.cs, UI/UI.csproj
The fixed `Content-Security-Policy` header added to resolve a warning raised during the IT health check cause the following non critical issues:
- Web assets built in developer mode (build:dev and watch) were blocked slowing down development
- Hot reload was similarly blocked and no longer worked
- Google Tag Manager injects scripts into the pages and these dynamic scripts were also blocked
No user facing changes.
Confirm that the local development experience is fully functional
https://dfedigital.atlassian.net/browse/NTP-593
=> NTP-593: Use NuGet package to add security headers and make compatible with GTM and local development

Infrastructure/Extensions/ServiceCollectionDevelopmentExtensions.cs, Infrastructure/Extensions/ServiceCollectionExtensions.cs, UI/Program.cs
A fresh clone without any previous local configuration fails the e2e tests for GTM cookies as the GTM cookie is only present once configuration has been added.
This PR adds the GTM configuration `GoogleAnalytics:MeasurementId` automatically when the project is run in development environment.
The `MeasurementId` value does not link to any real Google analytics project.
https://dfedigital.atlassian.net/browse/NTP-594
=> NTP-594: Add automatic configuration for GTM when in development env

Tests/SearchForAPostcode.cs, Tests/SearchForKeyStages.cs, Tests/SearchForSubjects.cs, UI/Pages/Index.cshtml, UI/Pages/Index.cshtml.cs, UI/Pages/WhichKeyStages.cshtml, UI/Pages/WhichKeyStages.cshtml.cs, UI/Pages/WhichSubjects.cshtml, UI/Pages/WhichSubjects.cshtml.cs, UI/cypress/e2e/cookies.feature
All search pages now submit their forms by GET so there is no longer a Resubmit Post question by the browser.
Using the browser's back button will simply show the cached version of the previous page.  When this page was originally showing an error due to invalid submission, this error will again be shown.
https://dfedigital.atlassian.net/browse/NTP-423
=> NTP-423: Prevent errors when going back to pages submitted with invalid data

UI/cypress/e2e/results.feature
Added end to end test for selecting subjects, which was failing before
https://dfedigital.atlassian.net/browse/NTP-537
=> NTP-537: Added end to end test for selecting subjects

.github/workflows/pull-request.yml, Infrastructure/Extensions/ServiceCollectionDevelopmentExtensions.cs, README.md, UI/Pages/Shared/_Layout.cshtml, UI/Pages/TuitionPartner.cshtml, UI/cypress/e2e/cookies.feature, UI/cypress/e2e/cookies.js, docker-compose.yml, manifest.yml, vars-pr.yml, vars-production.yml, vars-qa.yml, vars-research.yml, vars-staging.yml
The team would like to evaluate the extra control Google Tag Manager provides for tracking additional events. This spike evaluates the GTM onboarding process and code changes
https://dfedigital.atlassian.net/browse/NTP-443
=> NTP-443: Added configurable GTM integration

Infrastructure/DataEncryptionService.cs, Infrastructure/DataImporterService.cs
We're currently supressing specific warnings from creating alerts in Slack. This PR covers the ones related to the data import process by reducing the log levels from warning to information. The log lines in question were not indicating out of the ordinary actions or behaviour.
https://dfedigital.atlassian.net/browse/NTP-523
=> NTP-523: Reduce log level of data import related logging

Infrastructure/DataImport/GoogleDriveFileEnumerable.cs, Infrastructure/DataImport/GoogleDriveFileService.cs, Infrastructure/DataImporterService.cs, Tests/Importing/ImportLogoFiles.cs, UI/Properties/launchSettings.json
Logos were imported for a tuition partner if the logo filename contained the tuition partner's canonicalised name regardless of what else the filename contained.  Some tuition partners have similar names and logos were occasionally imported for the wrong partner.
This change ensures logo files must exactly match the canonicalised name plus a `Logo_` prefix.
The Equal Education Partners logo was showing for both Equal Education Partners but also Equal Education.  Now it only shows for the correct tuition partner
https://dfedigital.atlassian.net/browse/NTP-630
=> NTP-630: Ensure logos are matched to their exact tuition partner name

.github/workflows/import-data.yml, .github/workflows/nightly-import-data.yml, .github/workflows/pull-request.yml
The team would like to move to automatically running the data import process nightly removing the need for a developer to manually run the process and ensure that the TP data is up to date.
This cannot be fully proven until it's merged into main. Any issues will need to be fixed in subsequent PRs.
https://dfedigital.atlassian.net/browse/NTP-623
=> NTP-623: Add nightly run of the data import job to each environment

Application.Tests/Extensions/StringExtensionsTests.cs, Application/Extensions/StringExtensions.cs, UI/cypress/e2e/full-list.js
Some tuition partner names have characters that do not safe for URLs. A case in point is `Eric's Tutoring`. This results in the logos not appearing correctly as the browser looks for `eric%23s-tutoring` instead of `eric's-tutoring`.
The resolution is to remove all unsafe characters, resulting in `erics-tutoring`.
The ASPNet core engine does rely on the brace and parenthesis characters remaining untouched as they are used by the routing engine, and our renaming behaviour would break routing if these characters were removed.
https://dfedigital.atlassian.net/browse/NTP-632
=> NTP-632: URLs only contain URL safe characters

Application/INtpDbContext.cs, Tests/SearchForResults.cs, Tests/ShowAllTuitionPartners.cs, Tests/TestData/District.cs, Tests/TuitionPartnerDetailsPage.cs, Tests/Utilities/SliceFixture.cs, UI/Pages/AllTuitionPartners.cshtml, UI/Pages/AllTuitionPartners.cshtml.cs, UI/Pages/SearchResults.cshtml, UI/Pages/SearchResults.cshtml.cs, UI/Pages/TuitionPartner.cshtml, UI/Pages/TuitionPartner.cshtml.cs, UI/cypress/e2e/cookies.feature, UI/cypress/e2e/cookies.js, UI/cypress/e2e/full-list.js, UI/cypress/e2e/tuition-partner-user-journey.feature, UI/cypress/e2e/tuition-partner-user-journey.js, UI/cypress/support/step_definitions/call-to-action.js
When a search is done the postcode (and LADs) are stored in temp data/session and then used to filter the details that are shown on the TP details page.  The same page is also called from the full list of TPs, which should show nationwide data.  The issue is that it's still applying the previously searched postcode/LADs that are in temp data.  
The suggestion is to switch this to using the query string that is similar to the rest of the website.
To reproduce the issue do the following…
Do a search, with the following details
If you then search for “Action Tutoring” on this page it will not be found, since it does not supply tutoring for this postcode.
Return to the full list of tutors and do the following
Selecting the “Action Tutoring” TP shows the following, with the type of tuition and …
=> NTP-659: pricing info not displaying for t ps when do you offer tuition to all locations nationwide response is empty

Application.Tests/Extensions/StringExtensionsTests.cs, UI/cypress/support/utils.js
Error when running cypress tests since the end to end tests are out of date with the C# logic that sets the URL for the pages on import.  Spotted when a new "m2r Education" TP was added and the URL is "m-2r-education", but the cypress tests are using  "m2r-education"
Update cypress test logic so it cater for the new TP
Check this works by running the end-to-end tests
https://dfedigital.atlassian.net/browse/NTP-729
=> NTP-729: m2r education SEO URL is incorrect

UI/cypress/e2e/tuition-partner-details.feature
Cypress end to end tests broken when Lancashire County Council TP has been removed from the service
Update to be a different TP - “Pearson”
Run end to end tests
https://dfedigital.atlassian.net/browse/NTP-739
=> NTP-739: switch no phone number test to use pearson TP

Infrastructure/DataImporterService.cs, Infrastructure/Infrastructure.csproj
Ensure that the import does a retry if there are network issues when reading the spreadsheets from the Google drive
Use Polly nuget package to to wait and retry 5 times per file and if there are still issues then throw the exception and rollback the database changes
Not easy to test - there is commented out code that can be uncommented to replicate random issues with the call to get the spreadsheet data
https://dfedigital.atlassian.net/browse/NTP-648
=> NTP-648: Add retry for G Drive calls on import

Application.Tests/Extensions/StringExtensionsTests.cs, Application/Extensions/StringExtensions.cs, UI/cypress/e2e/tuition-partner-details.feature, UI/cypress/support/utils.js
A couple of the TP URLs (which is generated by their name) were not in the best format and could be tidied up…
CER, Monarch Education & Sugarman Education (Parent- Affinity Workforce Solutions): https://www.find-tuition-partner.service.gov.uk/tuition-partner/cer-monarch-education--sugarman-education-(parent--affinity-workforce-solutions) has a URL with double hyphens rather than single: cer-monarch-education--sugarman-education-(parent--affinity-workforce-solutions)
m2r Education: https://www.find-tuition-partner.service.gov.uk/tuition-partner/m-2r-education is shown as m-2r-education, but would be better as m-2-r-education
Update the SEO URL C# logic and the corresponding cypress js test logic to ensure that all of the exsiting TP URLs stay the same but the following work as specified: …
=> NTP-731: Tidy up TP URL format

Application.Tests/Extensions/StringExtensionsTests.cs, Application/Extensions/StringExtensions.cs, UI/cypress/support/utils.js
* NTP-731 - Tidy up TP URL format
* NTP-739: switch no phone number test to use pearson TP (#193) (#194)
=> NTP-731: Tidy up TP URL format (#191)

UI/Pages/TuitionPartner.cshtml.cs, UI/cypress/e2e/full-list.feature, UI/cypress/e2e/full-list.js
Issue with navigating to 3D Recruit TP details page.
Issue navigating to the 3D Recruit Ltd TP details page, getting a 404 error page.  Can be reproduced by clicking the “3D Recruit Ltd“ link from the following page [All Tuition Partners](https://www.find-tuition-partner.service.gov.uk/all-tuition-partners)
This is because there is a check on the TP details page to ensure that the URL format is correct when it loads this page.  The link is using “3d-recruit-ltd”, which is correct, since this is the correct SEO URL for the TP name of “3D Recruit Ltd“.  But the check on the TP details page is not formatting the TP name (e.g. “3D Recruit Ltd“) to compare against the passed in URL.  It is formatting the URL (so “3d-recruit-ltd” in this case) to ensure it is as excepted, but since it may be …
=> NTP-764: Resolve issue with 404 error on 3D Recruit Ltd TP details page

UI/Pages/Shared/_OptionsSelect.cshtml, UI/src/sass/option-select.scss
To reproduce:
Disable JS
Carry out a search and get to the results page
Attempt to change the subject checkboxes on the left side
Expected result:
At 3. The checkboxes can be changed and ‘Apply filters’ will update the results
Actual result:
At 3. The checkboxes cannot be clicked with the mouse (although they can be selected with the keyboard).
The issue is that the "Key Stage" filter headings (that collapse and expand the sections when js is enabled) is set as a an HTML button, which is correct when js is enabled, but by design it should be a span when js is disabled.   This then allows the checkboxes to be selected.  
The following component is used and details about this are on line 131 of the js file:
https://github.com/alphagov/finder-frontend/blob/main/app/assets/javascripts/componen …
=> NTP-717: Ensure checkboxes can be selected on filters with no js

UI/Pages/AcademicMentors.cshtml, UI/Pages/Accessibility.cshtml, UI/Pages/AllTuitionPartners.cshtml, UI/Pages/ContactUs.cshtml, UI/Pages/Cookies.cshtml, UI/Pages/Error.cshtml, UI/Pages/FundingAndReporting.cshtml, UI/Pages/Privacy.cshtml, UI/Pages/ReportIssues.cshtml, UI/Pages/SchoolLedTutoring.cshtml, UI/Pages/SearchResults.cshtml, UI/Pages/Shared/_Layout.cshtml, UI/Pages/TuitionPartner.cshtml, UI/Pages/WhichKeyStages.cshtml, UI/Pages/WhichSubjects.cshtml, UI/cypress/e2e/full-list.feature, UI/cypress/e2e/tuition-partner-details.feature, UI/src/index.scss
"Back" link is incorrectly inside the "main" HTML element - change to ensure meets GDS
Move the back, home and print to outside the main
The “Back” link and “Print this page” links are currently inside the "main" HTML element. The standard GDS layout [GOV.UK - Customised page template](https://design-system.service.gov.uk/styles/page-template/custom/index.html) has the Back link deliberately outside of the "main", sitting between the phase banner and the "main".
The “Back” link (and “Print this page” link if applicable) have been moved between the phase banner and main element on all pages.
The “Back” link is sitting in the correct page position, closer to the phase banner, and further from the h1 (as per attached image)
https://dfedigital.atlassian.net/browse/NTP-741
=> NTP-741: "Back" link is incorrectly inside the <main> element

UI/Pages/SearchResults.cshtml.cs, UI/Pages/SearchResults.cshtml.js
Using the browser navigation displays the incorrect counter information for the number of TP's Shortlisted
Prevent page for caching results.
When you use the browser navigation back button from the 'shortlist' page to go back 
to the 'searchresult' page, the counter should display the correct information of the number of shortlisted Tp's. 
[NTP-785](https://dfedigital.atlassian.net/jira/software/projects/NTP/boards/135/backlog?selectedIssue=NTP-785&text=785)
=> NTP-785: Using Browser Navigation Bug Fix

Tests/TuitionPartnerShortlistStorage/CookieBasedTuitionPartnerShortlistStorageTests.cs, UI/Pages/SearchResults.cshtml, UI/src/sass/search-result-page-shortlist.scss
Change the checkboxes used for adding tuition partners to the shortlist to GDS checkboxes.
Change how and where the checkboxes are displayed and use GDS checkboxes instead
The look and feel of the checkboxes used on the Search Result page should be that of a standard GDS checkbox.
[NTP-647](https://dfedigital.atlassian.net/jira/software/projects/NTP/boards/135?selectedIssue=NTP-647)
=> NTP-647: Add Comparing And Contrasting Make Checkbox Style Like GDS

UI/Pages/SearchResults.cshtml, UI/Pages/WhichKeyStages.cshtml, UI/Pages/WhichSubjects.cshtml, UI/cypress/e2e/results.js, UI/cypress/support/step_definitions/subjects-page.js
The GOV.UK Design System specifies that groups of checkboxes should have a fieldset element around checkboxes.
The checkboxes on the “Which key stages do you need tutoring support for?” and the “Which subjects do you need tutoring support for?” do not have these fieldsets.
Add Checkboxes Fieldset component around checkboxes
Browse to the WhichKeyStages page or/and the WhichSubjects page, 
the checkboxes should be contained in a Fieldset element. 
[NTP-742](https://dfedigital.atlassian.net/jira/software/projects/NTP/boards/135?selectedIssue=NTP-742)
=> NTP-742: Absent Fieldset bug-fix for WhichKeyStages & WhichSubjects pages

UI/Extensions/SearchModelExtensions.cs, UI/Filters/ExceptionLoggingMiddleware.cs, UI/Pages/Shortlist.cshtml, UI/Pages/Shortlist.cshtml.cs, UI/Pages/ShortlistClearConfirm.cshtml, UI/Pages/ShortlistClearConfirm.cshtml.cs, UI/Pages/TuitionPartner.cshtml.cs, UI/cypress/e2e/shortlist.feature, UI/cypress/e2e/shortlist.js, UI/src/sass/shortlist.scss
Removing TPs from the TP shortlist page
Allow each TP row on the shortlist to be removed
Allow the full list to be cleared via the link at the bottom and go via a confirmation page
Acceptance Criteria:
AC1: Clear short list link
GIVEN the shortlist TP  page has been displayed
WHEN the user selects ‘Clear my shortlist’ link
THEN display the warning page (according to the mock-up) 
AC2: Clear short list button
GIVEN the warning  page has been displayed
WHEN the user selects ‘Clear my shortlist’ button
THEN remove all shortlisted tuition partners from the shortlist and display the confirmation page (according to the mock-up)
AC3: Cancel link
GIVEN the warning  page has been displayed
WHEN the user selects  the ‘Cancel” link
THEN return user to the shortlist page 
AC4: Search results link …
=> NTP-755: Removing TPs from the TP shortlist page

UI/Pages/SearchResults.cshtml.js, UI/Pages/Shared/_Layout.cshtml
Service doesn't work correctly in IE11 because the code uses newer javascript code e.g. 'let'
Make it so that on IE11 the service shown to the user is the non-javascript version.
on IE11 the non-javascript version of the service should be shown. For example on the Search Result page
a button should be present to shortlist a tuition partner.
[NTP-794](https://dfedigital.atlassian.net/browse/NTP-794)
[NTP-794]: https://dfedigital.atlassian.net/browse/NTP-794?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> NTP-794: Set service to use non-JS code if running in IE

.github/workflows/pull-request.yml, UI/Pages/SearchResults.cshtml.js, UI/cypress/e2e/shortlist.feature, UI/cypress/e2e/shortlist.js
We have a race condition where the shortlist becomes inconsistent if another shortlist checkbox is selected before the result of a previous one has returned (due to the cookie storage). This is causing some e2e tests to randomly fail.
Chaining the promises for the shortlist updates so that it waits for the result of one to come back before starting the next.
https://dfedigital.atlassian.net/browse/NTP-837
=> NTP-837: Adding some promise chaining so that shortlisting works when checkboxes are selected rapidly

UI/cypress/e2e/shortlist.js
Is a nasty fix to ensure cypress tests do not fail, waiting for shortlist checkbox to complete before going to next test.
Builds on top of main fix https://github.com/DFE-Digital/find-a-tuition-partner/pull/222
Add 500ms wait after shortlist checkbox is selected on search results page, so that the UI and cookie can update before the next test.
Run cypress test
https://dfedigital.atlassian.net/browse/NTP-837
=> NTP-837: Adding some promise chaining so that shortlisting works when checkboxes are selected rapidly v2

Tests/SearchForResults.cs, Tests/ShortlistPageTests.cs, Tests/ShowAllTuitionPartners.cs, UI/Pages/SearchResults.cshtml.cs, UI/Pages/Shortlist.cshtml.cs, UI/cypress/e2e/privacy.feature, UI/cypress/e2e/results.feature, UI/cypress/e2e/results.js, UI/cypress/e2e/shortlist.feature, UI/cypress/e2e/subjects.feature, UI/cypress/support/step_definitions/shortlist-page.js
Fix a bug with the Invalid or Blank PostCode search on the results page.
This bug fix also covers the NTP-797: Shortlist page logs an error if the postcode is missing.
Ensure that when a search is carried out with a blank or invalid postcode on the 'search results page, the postcode validator validates the postcode and displays the appropriate validation error message.
Ensure on the 'shortlist page' If the postcode is blank or invalid, and then we send the user straight back to the 'search results page; the postcode validator validates the postcode and displays the appropriate validation error message.
Ensure that the postcode validation works on the 'search results' and 'shortlist' pages, and with a blank or invalid postcode, ensure the functionality works. Test with and without js …
=> NTP-798: Fix a bug with the Invalid or Blank PostCode search on the results page

UI/MediatR/Handlers/GetTuitionPartnerQueryHandler.cs
Currently, when someone passes an invalid tuition partner id not found on our system, we log a warning that creates an alert for us to look into that. As the tuition partner id is not found, an error classed as 404 error, we will log that as info instead of a warning that will not trigger an alert.
Change log level from warning to information when there is no TP found.
Ensure that when there is no TP found, the error is logged as information, and we do not get an alert for that error.
[https://dfedigital.atlassian.net/browse/NTP-863](https://dfedigital.atlassian.net/browse/NTP-863)
=> NTP-863: Reduce the 404 alerting when there is no TP found.

UI/MediatR/Handlers/GetTuitionPartnerQueryHandler.cs, UI/Pages/TuitionPartner.cshtml.cs
Currently, when someone passes an invalid tuition partner id not found on our system, we log a warning that creates an alert for us to look into that. As the tuition partner id is not found, an error classed as 404 error, we will log that as info instead of a warning that will not trigger an alert.
Change log level from warning to information when there is no TP found.
Ensure that when no Tuition Partner is found for a given id on the`TuitionPartner.cshtml.cs`, the error is logged as information, and we do not get an alert for that error.
[https://dfedigital.atlassian.net/browse/NTP-863](https://dfedigital.atlassian.net/browse/NTP-863)
=> NTP-863: Change log level from warning to info when no Tuition Partner is found

Application/Extensions/LocationFilterParametersExtensions.cs, Tests/SearchForAPostcode.cs, Tests/SearchForResults.cs, Tests/ShortlistPageTests.cs, UI/MediatR/Handlers/GetTuitionPartnerQueryHandler.cs, UI/Pages/Index.cshtml.cs, UI/Pages/SearchResults.cshtml.cs, UI/Pages/Shortlist.cshtml.cs, UI/cypress/e2e/postcode.feature, UI/cypress/e2e/results.feature, UI/cypress/e2e/shortlist.feature
'Enter a valid postcode' should read 'Enter a real postcode' as per GDS guidelines
When a user enters an invalid postcode, the error message says ‘Enter a valid postcode’. The use of ‘valid’ is against GDS guidelines for error messages: https://design-system.service.gov.uk/components/error-message/#be-clear-and-concise
We should use ‘Enter a real postcode’ as per the address pattern here: https://design-system.service.gov.uk/patterns/addresses/#error-messages
https://dfedigital.atlassian.net/browse/NTP-867
=> NTP-867: Changing 'Enter a valid postcode' to 'Enter a real postcode'

UI/MediatR/Handlers/GetTuitionPartnerQueryHandler.cs, UI/Pages/TuitionPartner.cshtml, UI/cypress/e2e/full-list.feature, UI/cypress/e2e/full-list.js, UI/cypress/support/commands.js, UI/cypress/support/step_definitions/results-page.js
Ordering for pricing by group sizes is not always correct on the TP details page, e.g. https://www.find-tuition-partner.service.gov.uk/tuition-partner/tutor-doctor-beeston-park
Ensure that the pricing is ordered by group size
Run updated end to end tests and check the "tutor-doctor-beeston-park" TP
https://dfedigital.atlassian.net/browse/NTP-868
=> NTP-868: No order by on the TP details price group

UI/cypress/e2e/shortlist.feature, UI/cypress/e2e/shortlist.js
The following TPs have been removed from the system and their data is used in the cypress end to end tests: "3D Recruit Ltd" and "Tutor Doctor Beeston Park"
These need to be updated to use different TP data.
Update tests to use new TP data
Run e-2-e tests via GitHub actions
https://dfedigital.atlassian.net/browse/NTP-918
=> NTP-918: Update end to end tests after TPs have been removed

Application.Tests/Extensions/DecimalExtensionsTests.cs, Application/Common/Models/SearchModel.cs, Application/Extensions/DecimalExtensions.cs, Application/Extensions/SpreadsheetExtensions.cs, Domain/Search/TuitionPartnersDataFilter.cs, Infrastructure/Factories/QualityAssuredSpreadsheetTuitionPartnerFactory.cs, Infrastructure/Factories/TribalSpreadsheetTuitionPartnerFactory.cs, Infrastructure/Services/TuitionPartnerService.cs, Tests/TuitionPartnerDetailsPagePriceTable.cs, UI/Extensions/GroupPriceExtensions.cs, UI/Extensions/SearchModelExtensions.cs, UI/Pages/Shortlist.cshtml, UI/Pages/Shortlist.cshtml.cs, UI/Pages/TuitionPartner.cshtml, UI/cypress/e2e/shortlist.feature, UI/cypress/e2e/shortlist.js, UI/cypress/e2e/vat.feature, UI/cypress/e2e/vat.js
Ensure that NTP shows VAT prices inc and exc VAT, especially when comparing prices
Added in if VAT is included, VAT is excluded or not applicable against the prices.
Add in a new drop down option to toggle between the VAT inclusive
And VAT exclusive prices
Default the drop down selection to inclusive of VAT
TP details page to have a label stating if VAT does not apply if this is the case, to match the table
Currently for VAT exempt companies: 
Currently for VAT inclusive companies:
As part of this ticket we will change the way that we store the prices in the NTP database, so that they are exclusive of VAT.
When showing VAT inclusive prices we will add 20% and round to the nearest penny as per:
https://www.gov.uk/hmrc-internal-manuals/vat-trader-records/vatrec12030#:~:text=If%20the%20VAT%20 …
=> NTP-921: Changes for VAT

Application/Commands/SendEnquirerEnquiryResponseReceivedEmailCommand.cs, Application/Common/DTO/EnquirerEnquiryResponseReceivedDto.cs, Application/Common/Interfaces/Repositories/IMagicLinkRepository.cs, Application/Common/Models/EnquiryResponseModel.cs, Domain/Enums/EmailTemplateType.cs, Infrastructure/Configuration/GovUkNotifyOptions.cs, Infrastructure/Repositories/MagicLinkRepository.cs, Infrastructure/Services/NotificationsClientService.cs, UI/Pages/EnquiryResponse.cshtml.cs, manifest.yml, vars-pr.yml, vars-production.yml, vars-qa.yml, vars-research.yml, vars-staging.yml
=> NTP-879: School user is informed when a response is received

Tests/Enquiry/Build/EnquirerEmailPageTests.cs, UI/Pages/Enquiry/Build/EnquirerEmail.cshtml, UI/Pages/Enquiry/Build/EnquirerEmail.cshtml.cs, UI/Pages/Enquiry/Build/EnquiryQuestion.cshtml.cs
Spotted 2 issues:
Curly quotes not displaying correctly in hint text when deployed (was OK locally) 
If get validation error on email step twice (e.g. empty email) then use back button to search the data is lost in the query string, so shows no postcode.
Also, unit test changes missed from previous PR review
=> NTP-897: provide email address bug fix

UI/Pages/Shared/_Layout.cshtml
Make sure that the back link is not shown if there is no link set
https://dfedigital.atlassian.net/browse/NTP-1035
=> NTP-1035: navigating to the contact us page form email enquiry has a redundant back button

Application/Common/Models/Enquiry/Build/CheckYourAnswersModel.cs, Application/Constants/StringConstants.cs, Application/Validators/Enquiry/Build/CheckYourAnswersModelValidator.cs, UI/Pages/Enquiry/Build/CheckYourAnswers.cshtml, UI/Pages/Enquiry/Build/CheckYourAnswers.cshtml.cs, UI/Pages/Shared/_CookiesOptionBanner.cshtml, UI/Pages/Shared/_Layout.cshtml, UI/src/sass/enquiry-build.scss
UI changes in CYA as in ticket - label renames, show new label names, show new error messages for missing key stage, subjects and tuition type and show message in place of missing data.
Code tidy up on CYA page to use gov components
Ensure that only 1 error summary shown at a time on UI due to a11y issues
https://dfedigital.atlassian.net/browse/NTP-1040
=> NTP-1040: UI changes and tidy up CYA page

Application/Common/Models/Enquiry/Respond/EnquirerViewResponseModel.cs, Application/Extensions/IntExtensions.cs, Infrastructure/Repositories/EnquiryRepository.cs, Infrastructure/Repositories/TuitionPartnerEnquiryRepository.cs, UI/Pages/Enquiry/Respond/AllEnquirerResponses.cshtml, UI/Pages/Enquiry/Respond/CheckYourAnswers.cshtml, UI/Pages/Enquiry/Respond/EnquirerResponse.cshtml, UI/Pages/Shared/_Layout.cshtml
With this PR, I have covered the below  tickets:
[https://dfedigital.atlassian.net/browse/NTP-1037](https://dfedigital.atlassian.net/browse/NTP-1037)
[https://dfedigital.atlassian.net/browse/NTP-1036](https://dfedigital.atlassian.net/browse/NTP-1036)
[https://dfedigital.atlassian.net/browse/NTP-1051](https://dfedigital.atlassian.net/browse/NTP-1051)
I have made separate commits to this PR against each ticket work above.
Regarding the NTP-1037 **AC_12_d** "View tuition partner’s contact details" when selected, the button takes the user to the TP contact details page is yet to be implemented, so once the work for the [https://dfedigital.atlassian.net/browse/NTP-1039](https://dfedigital.atlassian.net/browse/NTP-1039) is complete the button needs to be updated accordingly. …
=> NTP-1037: View a response

Application/Common/Models/Enquiry/Respond/ViewAndCaptureEnquiryResponseModel.cs, UI/Pages/Enquiry/Respond/Response.cshtml, UI/Pages/Enquiry/Respond/Response.cshtml.cs
https://dfedigital.atlassian.net/browse/NTP-1123
=> NTP-1123: On tp respond page the time to respond is set to somewhere near jesus 1st birthday if a validation error is shown

Application/Commands/AddEnquiryCommand.cs, Application/Commands/AddEnquiryResponseCommand.cs, Infrastructure/Repositories/EnquiryRepository.cs, UI/Pages/Enquiry/Build/SubmittedConfirmation.cshtml, UI/Pages/Enquiry/Respond/AllEnquirerResponses.cshtml, UI/Pages/Enquiry/Respond/CheckYourAnswers.cshtml, UI/Pages/Enquiry/Respond/EnquirerResponse.cshtml, UI/Pages/Enquiry/Respond/EnquirerViewTuitionPartnerDetails.cshtml, UI/Pages/Enquiry/Respond/Response.cshtml, UI/Pages/Enquiry/Respond/ResponseConfirmation.cshtml, UI/wwwroot/robots.txt
The dev team has decided on the below ACs for amending the routing of the enquiry build feature, particularly for the MVP.
ACs:
Enquirer View all:
`/enquiry/{ref_num}?Token=...`
Enquirer view specific:
`/enquiry/{ref_num}/{tp_name}?Token=...`
Enquirer TP reveal:
`/enquiry/{ref_num}/{tp_name}/contact-details?Token=...`
TP response:
`/enquiry-response/{tp_name}/{ref_num}?Token=...`
[https://dfedigital.atlassian.net/browse/NTP-1125](https://dfedigital.atlassian.net/browse/NTP-1125)
=> NTP-1125: Amend routing for the enquiry build feature

Application.Tests/Extensions/DateTimeExtensionsTests.cs, Application/Commands/AddEnquiryResponseCommand.cs, Application/Extensions/DateTimeExtensions.cs, Application/Extensions/DictionaryExtensions.cs, Infrastructure/Repositories/EnquiryRepository.cs
With this PR, we show the local date time for the enquiry build feature instead of displaying the UTC date time in the UI.
[https://dfedigital.atlassian.net/browse/NTP-1124](https://dfedigital.atlassian.net/browse/NTP-1124)
=> NTP-1124: Display date time in UI with the current local date time (UK).

Application/Validators/Enquiry/Build/AdditionalInformationModelValidator.cs, Application/Validators/Enquiry/Build/CheckYourAnswersModelValidator.cs, Application/Validators/Enquiry/Build/SENDRequirementsModelValidator.cs, Application/Validators/Enquiry/Build/TutoringLogisticsModelValidator.cs, Application/Validators/Enquiry/Respond/CheckYourAnswersModelValidator.cs, Application/Validators/Enquiry/Respond/ViewAndCaptureEnquiryResponseModelValidator.cs
…atch
https://dfedigital.atlassian.net/browse/NTP-1134
=> NTP-1134: Issue with text area count mismatch when using carriage returns

Application/Commands/Enquiry/Build/AddEnquiryCommand.cs, Application/Commands/Enquiry/Respond/AddEnquiryResponseCommand.cs, Application/Common/Interfaces/Repositories/IEnquiryRepository.cs, Application/Common/Interfaces/Repositories/ITuitionPartnerEnquiryRepository.cs, Application/Common/Models/Enquiry/EnquiryBaseModel.cs, Application/Common/Models/Enquiry/EnquiryResponseBaseModel.cs, Application/Common/Models/Enquiry/Manage/EnquirerViewAllResponsesModel.cs, Application/Common/Models/Enquiry/Manage/EnquirerViewResponseModel.cs, Application/Common/Models/Enquiry/Manage/EnquirerViewTuitionPartnerDetailsModel.cs, Application/Common/Models/Enquiry/Respond/CheckYourAnswersModel.cs, Application/Common/Models/Enquiry/Respond/EnquirerViewResponseModel.cs, Application/Common/Models/Enquiry/Respond/ViewAndCaptureEnquiryResponseModel.cs, Application/Queries/Enquiry/GetEnquirerViewAllResponsesQuery.cs, Application/Queries/Enquiry/IsValidMagicLinkTokenQuery.cs, Application/Queries/Enquiry/Manage/GetEnquirerViewResponseQuery.cs, Application/Queries/Enquiry/Manage/GetEnquirerViewTuitionPartnerDetailsQuery.cs, Infrastructure/Repositories/EnquiryRepository.cs, Infrastructure/Repositories/TuitionPartnerEnquiryRepository.cs, UI/Extensions/EnquiryResponseModelExtensions.cs, UI/Models/ResponsePageModel.cs, UI/Pages/Enquiry/Build/CheckYourAnswers.cshtml.cs, UI/Pages/Enquiry/Manage/AllEnquirerResponses.cshtml, UI/Pages/Enquiry/Manage/AllEnquirerResponses.cshtml.cs, UI/Pages/Enquiry/Manage/EnquirerResponse.cshtml, UI/Pages/Enquiry/Manage/EnquirerResponse.cshtml.cs, UI/Pages/Enquiry/Manage/EnquirerViewTuitionPartnerDetails.cshtml, UI/Pages/Enquiry/Manage/EnquirerViewTuitionPartnerDetails.cshtml.cs, UI/Pages/Enquiry/Respond/CheckYourAnswers.cshtml.cs, UI/Pages/Enquiry/Respond/Response.cshtml.cs
Restructure the code folders to align with the enquiry routes
Should the .NET code folder structure be restructured slightly - e.g. update “UI\Pages\Enquiry\Respond“ so that it is “UI\Pages\Enquiry\Respond“ and “UI\Pages\Enquiry\Manage“, so that the TP and enquirer pages and code are separated in a similar way to the routes.
Only changes are files being moved and namespaces updated - test that all correct
https://dfedigital.atlassian.net/browse/NTP-1164
=> NTP-1164: Restructure the code folders to align with the enquiry routes

.github/workflows/deploy-to-gpaas.yml, .github/workflows/import-data.yml, .github/workflows/pull-request-teardown.yml, .github/workflows/pull-request.yml
Undoes the temporary change where the CF CLI binaries were copied to a BLOB store as the CF CDN was broken for a time.
https://dfedigital.atlassian.net/browse/NTP-1183
=> NTP-1183: Change CF CLI binary back to the CF URL

UI/Pages/SearchResults.cshtml, UI/cypress/e2e/mobile.feature, UI/src/sass/print-this-page.scss, UI/src/sass/results-filter.scss
Change mobile version of search heading to match desktop
Change mobile version of search heading to match desktop
Run cypress test
https://dfedigital.atlassian.net/browse/NTP-1130
=> NTP-1130: Change mobile version of search heading to match desktop

scripts/export_enquiry_data.sh
We currently have an issue running the script for exporting anonymised enquiry data since the TuitionType column from the Enquires tables has been removed and is renamed to TuitionSettings as part of the following ticket: [https://dfedigital.atlassian.net/browse/NTP-1082](https://dfedigital.atlassian.net/browse/NTP-1082)
[https://dfedigital.atlassian.net/browse/NTP-1227](https://dfedigital.atlassian.net/browse/NTP-1227)
=> NTP-1227: Amend the script for exporting anonymised enquiry data

UI/Pages/Privacy.cshtml
Add use of Clarity to Privacy Statement
The privacy statement lists tools like Google Analytics that we use to analyse peoples data. We probably need to add the use of MS Clarity to this as we intend to use this.
- Use of Microsoft Clarity
- Clean up of bullet points where there is only one bullet point listed
- Date published
https://dfedigital.atlassian.net/browse/NTP-1222
=> NTP-1222: Add use of Clarity to Privacy Statement

Application/Common/Interfaces/INotificationsClientService.cs, Infrastructure/Services/NotificationsClientService.cs, Infrastructure/Services/ProcessEmailsService.cs
Fix so don't keep logging status update checks after 1st error is logged
Issue spotted in QA when deployed
Run against QA and ensure doesn't keep throwing errors after 1st error
https://dfedigital.atlassian.net/browse/NTP-1151
=> NTP-1151: Fix so don't keep logging status update checks after 1st error is logged

Application.Tests/Extensions/StringExtensionsTests.cs, Application/Extensions/StringExtensions.cs, Infrastructure/DataImporterService.cs, Infrastructure/Factories/TribalSpreadsheetTuitionPartnerFactory.cs, UI/Routing/SeoRouteConvention.cs, UI/cypress/support/utils.js
Fix URL creation if a TP has forward slash in their name and tweak alerts
A new TP has the name “Ravenspoint Ltd T/A Tutor Doctor Reading, Maidenhead, Wokingham“ the forward slash is causing an issue since we use this name to create the URL for the TP details.  So the / should be stripped out when used in the URL, otherwise the path is invalid.
We also spotted that if there is a missing logo we are not alerted (this is logged as info).  Since all TPs seem to have a logo we will log this as a warning (so will not stop upload, but we’ll be alerted), so we have visibility of the missing logo now that Tribal control the data maintenance for TPs.
Since the new spreadsheet successfully uploaded, we had an issue rolling back to the previous version.  This is because the old data could not be …
=> NTP-1244: Fix URL creation if a TP has forward slash in their name and tweak alerts

UI/Pages/SearchResults.cshtml, UI/Pages/Shared/_Layout.cshtml, UI/Pages/Shared/_TopLink.cshtml, UI/cypress/e2e/compare-list.feature, UI/cypress/e2e/compare-list.js, UI/cypress/support/step_definitions/results-page.js, UI/src/index.js, UI/src/index.scss, UI/src/javascript/back-to-top.js, UI/src/javascript/compare-list-checkbox.js, UI/src/sass/back-to-top.scss
Users may struggle to find the comparison list link if they are at the bottom of the page.
Add link that shows at top of page to return to top or view price compare list, like https://findapprenticeshiptraining.apprenticeships.education.gov.uk/courses
Test with js enabled and disabled, in desktop, tablet and mobile and check accessible
https://dfedigital.atlassian.net/browse/NTP-1112
=> NTP-1112: Users may struggle to find the comparison list link if they are at the bottom of the page.

scripts/export_enquiry_data.sh
Update the NTP data export script so includes some of the recent changes/data
There is an existing data export script that allows us to get the live enquiry data and do some analysis and/or help with any user enquiries that come via the helpdesk.  See [find-a-tuition-partner/scripts/export_enquiry_data.sh at main · DFE-Digital/find-a-tuition-partner](https://github.com/DFE-Digital/find-a-tuition-partner/blob/main/scripts/export_enquiry_data.sh) 
This export should include some of the data from the more recent changes, but after review could also be improved.
Update the script to:
Include the recent changes/data:
School name, postcode and LAD
If the TP has declined to respond
If the enquirer has rejected the response and if selected other the free text reason
The enquirers status set for a …
=> NTP-1246: Update the NTP data export script so includes some of the recent changes/data

Infrastructure/DataImporterService.cs
Update the TP importer to allow multiple spreadsheets to exist in Azure Blob storage and process latest
The importer currently expects 1 spreadsheet to exist in Azure Blob storage for the TP data.
Change this so we can have multiple versions of the spreadsheet sorted and process the latest (using the spreadsheet date in the name or maybe the created date - need to confirm this approach with Tribal).  This will mean it’s much easier to rollback should there be an issue - basically remove the latest version.
Update the Azure blob storage with multiple historical spreadsheets and ensure that it processes the most recent one.
https://dfedigital.atlassian.net/browse/NTP-1247
=> NTP-1247: Update the TP importer to allow multiple spreadsheets to exist in Azure Blob storage and process latest

terraform/azure/vars-production.tfvars
Reverts DFE-Digital/find-a-tuition-partner#398
=> Revert "NTP-1292: Fix Inconsistent Domain Resolution for https://www.find-tuition-partner.service.gov.uk"

.github/actions/terraform-apply-and-deployment/action.yml, .github/workflows/continuous-deployment-to-qa.yml, terraform/azure/modules/fatp_azure_web_app_services_hosting/key-vault.tf, terraform/azure/modules/fatp_azure_web_app_services_hosting/logic-app.tf, terraform/azure/modules/fatp_azure_web_app_services_hosting/logs-storage.tf, terraform/azure/modules/fatp_azure_web_app_services_hosting/monitor.tf, terraform/azure/modules/fatp_azure_web_app_services_hosting/postgresql.tf, terraform/azure/modules/fatp_azure_web_app_services_hosting/redis-cache.tf
This PR addresses a problem that was brought up in the prior PR: [https://github.com/DFE-Digital/find-a-tuition-partner/pull/397](https://github.com/DFE-Digital/find-a-tuition-partner/pull/397)
Pass the required vars to the continuous deployment QA workflow.
It also remove the deprecated `days` from the [azurerm_monitor_diagnostic_setting](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/monitor_diagnostic_setting#retention_policy) `retention_policy block`. The following issue talk about it further: [https://github.com/hashicorp/terraform-provider-azurerm/issues/23051](https://github.com/hashicorp/terraform-provider-azurerm/issues/23051)
[https://dfedigital.atlassian.net/browse/NTP-1288](https://dfedigital.atlassian.net/browse/NTP-1288)
=> NTP-1288: Pass the required vars to the continuous deployment QA workflow

UI/cypress.config.js, terraform/azure/modules/fatp_azure_web_app_services_hosting/key-vault.tf
Separate the key vault access policy from the primary `azurerm_key_vault` resource because it is unable to identify changes, such as the addition of a new access policy.
[https://dfedigital.atlassian.net/browse/NTP-1288](https://dfedigital.atlassian.net/browse/NTP-1288)
=> NTP-1288: Separate the key vault access policy from the primary `azurerm_key_vault` resource
