DFE-Digital/find-a-tuition-partner

UI/Pages/Shared/_OptionsSelect.cshtml, UI/src/sass/option-select.scss
Hover for Search Filters Where Not Working has Expected .In this PR Fixed the issue Which Causing Hover for Search Filter
Before:
After:
Make Sure filters are working as per after screenshot
https://dfedigital.atlassian.net/browse/NTP-436
=> NTP-436: Fixed the css issue for Search Result Filter

UI/Pages/SearchResults.cshtml, UI/Pages/WhichSubjects.cshtml, UI/cypress/e2e/results.feature, UI/cypress/e2e/results.js, UI/cypress/e2e/subjects.feature, UI/cypress/e2e/subjects.js, UI/cypress/e2e/tuition-partner-details.feature, UI/cypress/e2e/tuition-partner-details.js
Subjects in ''Which Subjects' and 'Search results' pages need to be in alphabetical order
**'Which subjects page before'**
**'Which subjects page after'**
**'Search results page before'**
**'Search results page after'**
[## Link to Jira ticket](https://dfedigital.atlassian.net/browse/NTP-431)
=> NTP-431: ordering the subject list in the results page

docs/testing-strategy.md
The alpha assessment technical recommendations suggested adding a testing strategy document which explained what tests were run against which environment and the approval steps to promote a deployment through environments.
The testing strategy here is based off a [reference example](https://dfedigital.atlassian.net/wiki/spaces/GGIT/pages/1925447713/Testing+Strategy+GIT+Website) recommended by the assessor.
[NTP-354](https://dfedigital.atlassian.net/browse/NTP-354)
=> NTP-431: Add testing strategy document

UI/Pages/Accessibility.cshtml, UI/Pages/Shared/_Layout.cshtml, UI/cypress/e2e/accessibility.feature, UI/cypress/e2e/accessibility.js, UI/cypress/e2e/postcode.feature, UI/cypress/e2e/postcode.js, UI/cypress/e2e/tuition-partner-details.feature
Content added to Accessibility page
Before:
After:
The Accessible statement page should match the Google Document attached  in the ticket  ntp-387 
https://dfedigital.atlassian.net/browse/NTP-387
=> NTP-387:Accessibility statement added for accessibility  page

.github/workflows/build-and-test.yml
We expect code to be formatted in accordance with the `dotnet format` tool.  This PR adds a build check that the code format does indeed match `dotnet format`.  This prevents the need for manual review of, and PR comments about formatting.
If the `dotnet format` tool would make alterations to the code, then a quality gate is failed and the PR is blocked.  A developer should then run the tool, and commit the changes.
=> Run dotnet format to ensure code compliance when building in CI

UI/Pages/Index.cshtml, UI/Pages/SearchResults.cshtml
* Index page has a new sentence for the School-led tutoring box
* Search results uses `Tuition partner information` for the description row heading
https://dfedigital.atlassian.net/browse/NTP-525
https://dfedigital.atlassian.net/browse/NTP-469
=> NTP-525: Content updates

UI/Pages/AcademicMentors.cshtml, UI/Pages/Accessibility.cshtml, UI/Pages/Cookies.cshtml, UI/Pages/FundingAndReporting.cshtml, UI/Pages/Privacy.cshtml, UI/Pages/SchoolLedTutoring.cshtml, UI/cypress/e2e/academicmentors.feature, UI/cypress/e2e/accessibility.feature, UI/cypress/e2e/cookies.feature, UI/cypress/e2e/fundingandreporting.feature, UI/cypress/e2e/postcode.feature, UI/cypress/e2e/privacy.feature, UI/cypress/e2e/schoolledtutoring.feature, UI/cypress/e2e/schoolledtutoring.js, UI/cypress/e2e/subjects.feature
A unique page title per page has been defined both to assist users and for Google Analytics.
Before:
After:
(NTP-513)[https://dfedigital.atlassian.net/browse/NTP-513]
=> NTP-513: HTML titles

UI/Pages/SearchResults.cshtml, UI/cypress/e2e/results.js
https://dfedigital.atlassian.net/browse/NTP-511
=> NTP-511: Remove period from search results sentence

UI/Pages/Cookies.cshtml, UI/Program.cs, UI/cypress/e2e/cookies.feature, UI/cypress/e2e/cookies.js
Cookies need renamed in line with application and user cookie information needs updating on the cookie page. 
Cookies renamed in line with application and user cookie information updated on the cookie page. 
Antiforgery cookie  name changed to .FindATuitionPartner.Antiforgery
.AspNetCore.Mvc.CookieTempDataProvider cookie name changed to .FindATuitionPartner.Mvc.CookieTempDataProvider
and added to cookie page. 
GA cookie '_ga_' added to cookie information on cookie page. 
**Before** 
**After**
[](https://dfedigital.atlassian.net/browse/NTP-510)
=> NTP-510 ga cookies to match what we have in our cookies page

UI/Pages/TuitionPartner.cshtml
Following a review by members of the team, some content errors have been spotted on the TP information page. This just needs a quick content update.
Before:
After:
content change should meet the ac's acceptance criteria
https://dfedigital.atlassian.net/browse/NTP-541
=> NTP-541:Content update on tuition partner details page

UI/Pages/AcademicMentors.cshtml, UI/cypress/e2e/academicmentors.feature, UI/cypress/e2e/academicmentors.js
Content update to Academic mentors page
https://dfedigital.atlassian.net/browse/NTP-584
=> NTP-584: Content for academic mentors

UI/Pages/SchoolLedTutoring.cshtml
Added a line of content to the School led tutoring page.
https://dfedigital.atlassian.net/browse/NTP-581
=> NTP-581: Add content for booking tutors directly

UI/Pages/ContactUs.cshtml
Content changes added 
**Before:**
**After:**
https://dfedigital.atlassian.net/browse/NTP-580
=> NTP-580: Added bullet point changes to contact us

README.md, docs/runbooks/disaster-recovery.md
Disaster recovery documentation has been requested as part of the Authorisation To Operate process.
https://dfedigital.atlassian.net/browse/NTP-354
=> NTP-354: Disaster recovery runbook

UI/Pages/SearchResults.cshtml, UI/cypress/e2e/print-page.feature, UI/src/sass/mobile-views.scss, UI/src/sass/print-this-page.scss, UI/src/sass/results-filter.scss
'Print this page' link for the search results page.
https://dfedigital.atlassian.net/browse/NTP-575
=> NTP-575: Results page print link

UI/Pages/AcademicMentors.cshtml, UI/Pages/Accessibility.cshtml, UI/Pages/FundingAndReporting.cshtml, UI/Pages/Index.cshtml, UI/Pages/Privacy.cshtml, UI/Pages/TuitionPartner.cshtml
Updated content for various pages
https://dfedigital.atlassian.net/browse/NTP-579
=> NTP-578: Content updates

Application.Tests/Application.Tests.csproj, Application/Application.csproj, DataImporter/DataImporter.csproj, Domain.Tests/Domain.Tests.csproj, Domain/Domain.csproj, GiasPostcodeSearch/GiasPostcodeSearch.csproj, GiasPostcodeSearch/GiasPostcodeSearchService.cs, Infrastructure.Tests/Infrastructure.Tests.csproj, Infrastructure/Infrastructure.csproj, Tests/Tests.csproj, Tests/TuitionPartnerDetailsPage.cs, UI/Pages/Shared/_Layout.cshtml, UI/Pages/TuitionPartner.cshtml, UI/Pages/WhichSubjects.cshtml.cs, UI/UI.csproj
https://dfedigital.atlassian.net/browse/NTP-403
=> NTP-403: Turn on warnings as errors

GiasPostcodeSearch/GiasPostcodeSearchService.cs
=> NTP-403: Code review changes

.github/workflows/import-data.yml
=> NTP-599: Fix data import GitHub action

Domain/Search/TuitionPartnerSearchResult.cs, Tests/ShowAllTuitionPartners.cs, UI/Pages/AcademicMentors.cshtml, UI/Pages/AllQualityAssuredTuitionPartners.cshtml, UI/Pages/AllQualityAssuredTuitionPartners.cshtml.cs, UI/Pages/FullList.cshtml, UI/Pages/FullList.cshtml.cs, UI/Pages/Index.cshtml, UI/Pages/Privacy.cshtml, UI/Pages/TuitionPartner.cshtml, UI/Pages/TuitionPartner.cshtml.cs, UI/cypress/e2e/academicmentors.feature, UI/cypress/e2e/academicmentors.js, UI/cypress/e2e/full-list.feature, UI/cypress/e2e/full-list.js, UI/cypress/e2e/print-page.feature, UI/cypress/e2e/privacy.feature, UI/cypress/e2e/privacy.js, UI/cypress/e2e/reportissues.feature, UI/cypress/e2e/reportissues.js, UI/cypress/e2e/schoolledtutoring.feature, UI/cypress/e2e/schoolledtutoring.js, UI/cypress/e2e/tuition-partner-details.feature, UI/cypress/e2e/tuition-partner-details.js, UI/cypress/support/step_definitions/call-to-action.js, UI/cypress/support/step_definitions/pages.js, UI/src/sass/print-this-page.scss
Schools with pre existing relationships with Tuition Partners need to be able to check that their TP is assured. This is required to receive funding. This requirement has been implemented as a full list linked from the service start page.
https://dfedigital.atlassian.net/browse/NTP-605
=> NTP-605: All quality-assured tuition partners

Application/Handlers/SearchTuitionPartnerHandler.cs, Domain/Search/TuitionPartnerSearchRequest.cs, Tests/SearchForResults.cs, Tests/ShowAllTuitionPartners.cs, UI/Models/SearchModelAsQueryStringDictionary.cs, UI/Pages/AllTuitionPartners.cshtml, UI/Pages/AllTuitionPartners.cshtml.cs, UI/Pages/FullList.cshtml, UI/Pages/FullList.cshtml.cs, UI/Pages/Index.cshtml, UI/Pages/SearchModel.cs, UI/Pages/SearchResults.cshtml.cs, UI/Pages/TuitionPartner.cshtml, UI/Pages/TuitionPartner.cshtml.cs, UI/cypress/e2e/full-list.feature, UI/cypress/e2e/full-list.js, UI/cypress/support/step_definitions/pages.js, UI/src/sass/results-filter.scss
https://dfedigital.atlassian.net/browse/NTP-607
=> NTP-607: Search full list of tuition partners by name

README.md, docs/errors-and-bugs.md
=> NTP-603: Add errors and bugs process

.github/workflows/import-data.yml, .github/workflows/nightly-import-data.yml
=> NTP-623: Pass secrets from nightly import action to called action

Tests/ShowAllTuitionPartners.cs, Tests/Utilities/SliceFixture.cs, UI/Pages/AllTuitionPartners.cshtml, UI/cypress/e2e/full-list.feature, UI/cypress/e2e/full-list.js, UI/src/sass/tuition-partner-logo.scss
https://dfedigital.atlassian.net/browse/NTP-628
=> NTP-628: Add logos on the All Tuition Partners page

UI/cypress/support/utils.js
End to end tests are failing as the code used to calculate the kebab cased version of Tuition Partners' names did not match.
=> Ensure kebab case algorithm used in service code and end to end test matches

.github/workflows/deploy-to-gpaas.yml, .github/workflows/pull-request.yml, FindATuitionPartner.sln, Infrastructure/Configuration/GoogleDrive.cs, Infrastructure/DataImport/GoogleDriveDataFileEnumerable.cs, Infrastructure/DataImport/GoogleDriveFileEnumerable.cs, Infrastructure/DataImport/GoogleDriveLogoFileEnumerable.cs, Infrastructure/DataImport/Import.cs, Infrastructure/DataImporterService.cs, Infrastructure/Factories/GoogleDriveServiceFactory.cs, README.md, SearchMetricsMapper/Configuration/SearchMetrics.cs, SearchMetricsMapper/Program.cs, SearchMetricsMapper/Properties/launchSettings.json, SearchMetricsMapper/SearchMetric.cs, SearchMetricsMapper/SearchMetricMap.cs, SearchMetricsMapper/SearchMetricsMapper.csproj, SearchMetricsMapper/SearchMetricsMapperService.cs, docs/runbooks/import-tuition-partner-data.md, manifest.yml
=> Search metrics mapper and restore using directory ids for TP data and logo folders

UI/src/sass/tuition-partner-logo.scss
=> Use fixed image width of 180px for logo on Tuition Partner details page

UI/cypress/e2e/tuition-partner-details.feature
=> NTP-739: switch no phone number test to use pearson TP (#193)

UI/Pages/Shortlist.cshtml, UI/Pages/Shortlist.cshtml.cs, UI/Pages/TuitionPartner.cshtml, UI/Pages/TuitionPartner.cshtml.cs, UI/cypress/e2e/tuition-partner-details.feature, UI/cypress/e2e/tuition-partner-details.js
=> NTP-733: Ensure LA name is shown on TP details and shortlist page

UI/Pages/Cookies.cshtml, UI/Services/TuitionPartnerShortlistStorage/CookieBasedTuitionPartnerShortlistStorage.cs
On the cookie page:
The correct information about all the cookies used should be displayed.
- Change the Cookie name from ‘.FindATuitionPartner.search-page.shortlistedTps' to  '.FindATuitionPartner.Shortlist’
- Update provided details for ‘.FindATuitionPartner.Mvc.CookieTempDataProvider’ cookie, to reflect what it’s currently used for.
On the cookie page:
- The summary of the two named cookies should provide/display the correct detail of what they are used for.
- The name change for ‘.FindATuitionPartner.Mvc.CookieTempDataProvider’ should be reflected.
[NTP-788](https://dfedigital.atlassian.net/jira/software/projects/NTP/boards/135/backlog?selectedIssue=NTP-788&text=788)
=> NTP-788: Update Cookie Name Details

UI/Extensions/SearchModelExtensions.cs, UI/Filters/ExceptionLoggingMiddleware.cs, UI/Models/SearchModel.cs, UI/Pages/Shortlist.cshtml, UI/Pages/Shortlist.cshtml.cs, UI/Pages/ShortlistClearConfirm.cshtml, UI/Pages/ShortlistClearConfirm.cshtml.cs, UI/Pages/TuitionPartner.cshtml.cs, UI/cypress/e2e/shortlist.feature, UI/cypress/e2e/shortlist.js, UI/src/index.scss, UI/src/sass/print-this-page.scss, UI/src/sass/shortlist.scss
Ordering of columns on shortlist - for name and price table columns
Add TPs to shortlist then use the Name and Price column sorting to ensure works as planned.
https://dfedigital.atlassian.net/browse/NTP-740
=> NTP-740: Ordering of columns on shortlist

Infrastructure/MetricLogging/LoggingTuitionPartnerService.cs
Remove warning logs for 404 and ensure just log as info
Remove warning logs for 404 and ensure just log as info
Go to TP page with invalid TP name and ensure logs as info not warning
https://dfedigital.atlassian.net/browse/NTP-808
=> NTP-808: Adding logging for 404 errors

UI/Pages/ContactUs.cshtml, UI/Pages/Shared/_Layout.cshtml, UI/cypress/e2e/contactus.feature, UI/cypress/e2e/contactus.js, UI/cypress/e2e/footer.feature, UI/cypress/e2e/footer.js, UI/cypress/support/commands.js, UI/cypress/support/step_definitions/pages.js, UI/cypress/support/utils.js
Update the Contact us page as per the new content supplied.
- Amend the 'Contact us' page with new content supplied.
- Remove blue 'contact us' banner
- Create a 'Contact us' link positioned as the first link of the footer
- Create a 'Report issues' link on the right-hand side of the footer
Ensure the new amended content is reflected on the 'Contact us' page. Also, ensure the changes proposed with this PR is satisfactory. Test with and without js enabled on mobile and check accessibility.
[https://dfedigital.atlassian.net/browse/NTP-768](https://dfedigital.atlassian.net/browse/NTP-768)
=> NTP-768: Update the Contact us page as per the acceptance criteria of the ticket

UI/Pages/Cookies.cshtml, UI/Pages/Index.cshtml, UI/Pages/Shared/_QualityAssuredDetails.cshtml, UI/Pages/Shortlist.cshtml, UI/Pages/TuitionPartner.cshtml, UI/cypress/e2e/postcode.feature, UI/cypress/e2e/postcode.js, UI/cypress/e2e/tuition-partner-details.feature, UI/cypress/e2e/tuition-partner-details.js, UI/cypress/support/step_definitions/pages.js
Content change for quality assured text
Update text as per content request and ensure that the table captions are included but hidden
Review code and website
https://dfedigital.atlassian.net/browse/NTP-626
=> NTP-626: What is a quality assured tuition partner drop down

UI/Pages/Cookies.cshtml, UI/Pages/Session/Clear.cshtml, UI/Pages/Session/KeepAlive.cshtml, UI/Pages/Session/Timeout.cshtml, UI/Pages/Shared/_Layout.cshtml
=> NTP-967: Content update

UI/Pages/Enquiry/Build/Guidance.cshtml
https://dfedigital.atlassian.net/browse/NTP-985
=> NTP-985: Guidance page

UI/Pages/Index.cshtml, UI/cypress/e2e/full-list.feature, UI/cypress/e2e/full-list.js, UI/cypress/e2e/guidance-page.feature, UI/cypress/e2e/mobile.feature, UI/cypress/e2e/mobile.js, UI/cypress/e2e/postcode.feature, UI/cypress/e2e/tuition-partner-user-journey.feature, UI/cypress/e2e/tuition-partner-user-journey.js, UI/cypress/support/step_definitions/pages.js
[https://dfedigital.atlassian.net/browse/NTP-957](https://dfedigital.atlassian.net/browse/NTP-957)
=> NTP-957: Understand 'build an enquiry' is an option from the home-page

UI/src/javascript/results-filter.js
=> NTP-1014 updating the filter search results on the search results page doesnt update the compare prices page information

Application/Common/Models/Enquiry/Build/CheckYourAnswersModel.cs, Application/Queries/GetSearchLocationQuery.cs, Application/Validators/Enquiry/Build/CheckYourAnswersModelValidator.cs, Tests/Enquiry/Build/CheckYourAnswersTests.cs, UI/Extensions/HttpRequestExtensions.cs, UI/Pages/CompareList.cshtml.cs, UI/Pages/Enquiry/Build/CheckYourAnswers.cshtml, UI/Pages/Enquiry/Build/CheckYourAnswers.cshtml.cs, UI/Pages/Enquiry/Build/SubmittedConfirmation.cshtml.cs, UI/Pages/Enquiry/Respond/AllEnquirerResponses.cshtml.cs, UI/Pages/Enquiry/Respond/EnquirerResponse.cshtml, UI/Pages/Enquiry/Respond/Response.cshtml.cs, UI/Pages/WhichTuitionTypes.cshtml.cs, UI/src/index.scss, UI/src/sass/core.scss, UI/src/sass/enquiry-build.scss
Check & send my enquiry
https://dfedigital.atlassian.net/browse/NTP-943
=> NTP:943 check send my enquiry

UI/Pages/Enquiry/Build/Guidance.cshtml, UI/Pages/Enquiry/Build/SubmittedConfirmation.cshtml, UI/Pages/Enquiry/Respond/AllEnquirerResponses.cshtml, UI/Pages/Enquiry/Respond/EnquirerResponse.cshtml, UI/Pages/Enquiry/Respond/Response.cshtml
https://dfedigital.atlassian.net/browse/NTP-1113
=> NTP-1113: Team review mop up static content updates

UI/Program.cs
Session cookie should be secure, in fact all cookies should be secure
Update all cookies so when set are secure
Review cookie in the dev tools and make sure no impact on site 
https://dfedigital.atlassian.net/browse/NTP-1139
=> NTP-1139: All cookies should be secure

UI/Extensions/HttpContextExtensions.cs, UI/Pages/Enquiry/Respond/AllEnquirerResponses.cshtml.cs, UI/Pages/Enquiry/Respond/CheckYourAnswers.cshtml.cs, UI/Pages/Enquiry/Respond/EnquirerResponse.cshtml.cs, UI/Pages/Enquiry/Respond/EnquirerViewTuitionPartnerDetails.cshtml.cs, UI/Pages/Enquiry/Respond/Response.cshtml.cs, UI/Pages/Enquiry/Respond/ResponseConfirmation.cshtml.cs
Update the Data that is passed to Big Query, since some is now in the URLs
To remove logic from the code that is no longer needed since ends up with duplicate data in Big Query
- LocalAuthorityDistrictName:
- TP Enquiry response:
- /enquiry-response/{tp_name}/{ref_num}/confirmation - Removed from Data, now just in query string
- TuitionPartnerName:
- TP Enquiry response:
- /enquiry-response/{tp_name}/{ref_num}/check-your-answers - Removed Data on POST, since is now part of URL
- Enquirer view responses:
- /enquiry/{ref_num}/{tp_name} - Removed from Data, since is now part of URL
- /enquiry/{ref_num}/{tp_name}/contact-details - Removed from Data, since is now part of URL
- EnquirySupportReferenceNumber:
- TP Enquiry response:
- /enquiry-response/{tp_name}/{ref_num} - Removed from Data, …
=> NTP-1163: Review custom data sent to big query for enquiry now the url route include certain information

UI/cypress/e2e/compare-list.feature, UI/cypress/e2e/compare-list.js, UI/cypress/e2e/print-page.feature, UI/cypress/e2e/tuition-partner-details.feature, UI/cypress/fixtures/tplist.json, UI/cypress/support/commands.js
[https://dfedigital.atlassian.net/browse/NTP-1200](https://dfedigital.atlassian.net/browse/NTP-1200)
=> NTP-1200: Fix the E2E test after removing a few TPs

UI/Pages/Enquiry/Manage/EnquirerResponse.cshtml
Typo on Manage your interest
Change "Mange" to "Manage"
Review UI
[](https://dfedigital.atlassian.net/browse/NTP-1284)
=> NTP-1284: Typo on Manage your interest

Application.Tests/Extensions/StringExtensionsTests.cs, Application/Extensions/StringExtensions.cs, Infrastructure/Factories/TribalSpreadsheetTuitionPartnerFactory.cs
Update importer to work with change to Tribal spreadsheet format (delivery columns merging)
TP spreadsheet format has changed, 2 columns on Delivery tab being merged in to 1 column
Test the importer with new data
https://dfedigital.atlassian.net/browse/NTP-1233
=> NTP-1233: Update importer to work with change to Tribal spreadsheet format (delivery columns merging)

vars-production.yml
=> Turn the GPaaS site maintenance mode on for production

vars-production.yml
Reverts DFE-Digital/find-a-tuition-partner#382
=> Revert "Turn the GPaaS site maintenance mode on for production"

.github/workflows/continuous-deployment-to-qa.yml, .github/workflows/import-data.yml
Add Azure cli login action on the workflows with the correct values i.e passing the action input from the secret.
[https://dfedigital.atlassian.net/browse/NTP-880](https://dfedigital.atlassian.net/browse/NTP-880)
=> NTP-880: Fixing Issues Arising from Post-Platform Migration to Azure V4

.github/workflows/continuous-deployment-to-qa.yml, .github/workflows/nightly-import-data.yml
Post platform migration issue:
-  Specify the qa environment name so it can run the e2e test on that workflow.
- Add steps to run the database migration and data importer on the nightly import data workflow, as the import data workflow file won't work.
[https://dfedigital.atlassian.net/browse/NTP-880](https://dfedigital.atlassian.net/browse/NTP-880)
=> NTP-880: Fixing Issues Arising from Post-Platform Migration to Azure V5
